# Generated by Django 5.2.6 on 2025-10-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_type", models.CharField(max_length=100)),
                ("case_number", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                ("parties_names", models.TextField(blank=True, null=True)),
                ("filing_date", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "next_hearing_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "case_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_response", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
